### PR TITLE
fix:  show 'missing project' - not 'log in' - when current is inexistant (#715, #719)

### LINKED ISSUE #715: bug: Changing current active project to a non-existent one
[kind/bug]

## What versions of software are you using?
- Operating System: Ubuntu 22 
- IntelliJ version: ULTIMATE 2023.3.4 
- Extension version: 1.7.3-20240222
- Are you targeting a kubernetes or an Openshift cluster ? If possible, provide its version:
Server: https://api.sandbox-m4.g2pi.p1.openshiftapps.com:6443
OpenShift: 4.14.1
Kubernetes: v1.27.6+f67aeb3

## What did you run exactly?
Change current active project to a project which is non-existent or has not been created yet.
Screenshot from 2024-02-22 23-29-20

## Actual behavior
Success notification appears:
Screenshot from 2024-02-22 23-29-37

After the notification , I got **logged out** of the cluster 
Screenshot from 2024-02-22 23-30-07

## Expected behavior maybe ?

Don't allow user to press "Change" button if project doesn't exist in the "Change Active Project" dialog.  This failure to change the project also logs out of the cluster which could not be the desired behavior imo.

### LINKED ISSUE #719: bug: Missing 'No project available' when logged in to a cluster with no project.
[kind/bug]

## What versions of software are you using?
- Operating System: Ubuntu 22 
- IntelliJ version: ULTIMATE 2023.3.4 
- Extension version: 1.7.3-20240222
- Are you targeting a kubernetes or an Openshift cluster ? If possible, provide its version:

```
/home/mszuc/.odo/cache/3.15.0/odo version
odo v3.15.0 (10b5e8a8f)

Server: https://api.crc.testing:6443
Kubernetes: v1.27.8+4fab27b
Podman Client: 4.9.3
```

## What did you run exactly?

1. Log in to openshift local cluster, cluster was just created and has no projects on it
2. IJ Openshift says 'Please log in to the cluster' when login is correct it just has no project.
3. Creating project through intellij is not possible because 'Please log in to the cluster' so i create one with oc new-project
4. Once we create  project the IJ  Openshift tree gets refreshed  and works as expected behavior.
 
## Actual behavior
[noproject.webm](https://github.com/redhat-developer/intellij-openshift-connector/assets/100486753/1ef519e5-0bec-478a-8bf0-f21a002598d7)

Logged in to a cluster with no projects says we should 'Log in to the cluster'

## Expected behavior

Once user is logged in to a cluster with no project a message with 'No projects' would be nice and being able to create the project with IJ Openshift. 

I also believe this issue is related to https://github.com/redhat-developer/intellij-openshift-connector/issues/717

### PR DESCRIPTION
**Pull request by adietish**
fixes #715 
fixes #719

### CODE REVIEW

**Review by martinszuc — APPROVED** [review]
Tested these changes successfully, looks great to me.

**Comment by adietish** [comment]
rebased, re-adding "approved" etc.

**Pull request merged**
