### PR TITLE
chore: bump to latest IC version

### PR DESCRIPTION
**Pull request by adietish**
bump to latest IC-2023.2

### CODE REVIEW

**Comment by sbouchet** [comment]
@adietish : the windows build still fails after 3 attempt with the same error. definitely something wrong with IC2023-2 and windows? we might ask for QE to test this PR. CC @olkornii @lgrossma

**Comment by lgrossma** [comment]
How can I be of service?

**Comment by sbouchet** [comment]
@lgrossma we need someone with windows machine to test/run integration tests on Windows

**Comment by lgrossma** [comment]
@sbouchet sure, not problem. I have a spare windows machine. just tell me how to run the tests

**Comment by adietish** [comment]
> just tell me how to run the tests

```
./gradlew clean integrationTest -DideaVersion=IC-2023.2
```

**Comment by lgrossma** [comment]
@adietish So I tried running the integration tests on win10 and got same errors..
[log.txt](https://github.com/redhat-developer/intellij-openshift-connector/files/12834533/log.txt)

**Comment by adietish** [comment]
@lgrossma I dont have windows, can anyone in QE please investigate/fix?

**Comment by sbouchet** [comment]
from Jetbrains issue tracker (https://youtrack.jetbrains.com/issue/IDEA-325466/UI-scale-must-be-precomputed), on 2023.2 we must pass `java.awt.headless=true` as JVM parameter

**Comment by adietish** [comment]
@sbouchet, @lgrossma: I cannot reproduce the issue (jetbrains issue confirms that it wont happen on mac nor older ubuntu). Can you please verify it?

**Review by sbouchet — APPROVED** [review]
LGTM. the workaround made the test under windows to pass.

**Pull request merged**
