### PR TITLE
fix: report 'cluster unreachable' instead of 'failed to list secrets' (#682)

### LINKED ISSUE #682: If cluster is down, resource tree reports a failing operation to list secrets
**Steps:**
1. ASSERT: have the current context (in kube config) pointing to a cluster that is down
2. EXEC: launch plugin

**Result:**
The child node to the cluster node reports failing to list secrets.
image

**Expected result:**
It should report that the cluster is down.

### PR DESCRIPTION
**Pull request by adietish**
fixes #682

### CODE REVIEW

**Review by sbouchet — APPROVED** [review]
LGTM. nice to see new coverage, too !

**Comment by adietish** [comment]
/override "Conventional Commits PR Check / Aggregated Test Report (pull_request_target)"

**Pull request merged**
