### PR TITLE
chore: add helm cli workflow check

### PR DESCRIPTION
**Pull request by sbouchet**
## What is the purpose of this change? What does it change?
provide similar updates as odo checks

## Was the change discussed in an issue?
fixes #???

### CODE REVIEW

**Comment by adietish** [comment]
@sbouchet: the following IT seems to consistently fail. Is this expected?

```
Test checkCreateComponentAndDebug[feature: org.jboss.tools.intellij.openshift.utils.odo.ComponentFeature@a3b6218] FAILED (15m 44s)
```

**Comment by sbouchet** [comment]
> @sbouchet: the following IT seems to consistently fail. Is this expected?
> 
> ```
> Test checkCreateComponentAndDebug[feature: org.jboss.tools.intellij.openshift.utils.odo.ComponentFeature@a3b6218] FAILED (15m 44s)
> ```

no, its related to gitHub runners. re running the job makes it pass

**Pull request merged**
