### PR TITLE
fix: Update helm to 3.12.1

### PR DESCRIPTION
**Pull request by sbouchet**
See https://mirror.openshift.com/pub/openshift-v4/clients/helm

### CODE REVIEW

**Review by adietish — APPROVED** [review]

**Comment by sbouchet** [comment]
@adietish : 3.12 serach test is failling.
locally, i can reproduce, 3.12 returns a wrong json file. 
see atttached 
[11.txt](https://github.com/redhat-developer/intellij-openshift-connector/files/14792146/11.txt)
[12.txt](https://github.com/redhat-developer/intellij-openshift-connector/files/14792147/12.txt)

**Comment by sbouchet** [comment]
seems that helm binaries on redhat gateway is the culprit, from https://github.com/helm/helm/issues/12625
downloaded the helm binary from official repo https://github.com/helm/helm/releases/tag/v3.12.1 and json looks ok 
[12.helm.txt](https://github.com/redhat-developer/intellij-openshift-connector/files/14792307/12.helm.txt)

**Comment by sbouchet** [comment]
closing in favor of #796, that works without any commons modification

**Pull request closed without merging**
