### PR TITLE
test: Run UI tests with IJ 2024.1

### LINKED ISSUE #834: test: Run UI integration tests with IntelliJ 2024.1

### PR DESCRIPTION
**Pull request by richard0202**
fixes #834

### CODE REVIEW

**Comment by sbouchet** [comment]
@richard0202 : can you provide a link to the fork Integration test results ?

**Comment by richard0202** [comment]
@sbouchet Sure, there: https://github.com/richard0202/intellij-openshift-connector/actions/runs/9644912106

**Review by sbouchet — APPROVED** [review]
LGTM

**Pull request merged**
