### PR TITLE
feat: Add registry management

### LINKED ISSUE #271: Add registry management
[kind/Feature]

## Which functionality do you think we should add?

We should be able to manage devfile registries:

- add a new devfile registry
- remove an existing devfile registry
- edit an existing devfile registry

## Why is this needed?

Since we moved to devfiles

See also https://issues.redhat.com/browse/JBIDE-27610

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #271

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

## Was the change discussed in an issue?
fixes #???

### CODE REVIEW

**Review by sbouchet — CHANGES_REQUESTED** [review]
Tested and got some questions:
- when adding this registry (https://registry.devfile.io/), I can't get any children's. is this one supported ? 
- when creating component from empty project and want to use starter, I get the following display errors) 
Capture d’écran de 2021-05-31 15-16-07

**Comment by jeffmaury** [comment]
> 
> 
> Tested and got some questions:
> 
>     * when adding this registry (https://registry.devfile.io/), I can't get any children's. is this one supported ?
> 
>     * when creating component from empty project and want to use starter, I get the following display errors)
>       Capture d’écran de 2021-05-31 15-16-07

You need a recent version of odo to support non Git based registries.
Fixes the starter display issue so we should be good

**Comment by sbouchet** [comment]
> 
> You need a recent version of odo to support non Git based registries.
 ok , my PR for #309 is almost ready. i'll rebase it when this one will be merged.

> Fixes the starter display issue so we should be good
Ok, trying again

**Review by sbouchet — APPROVED** [review]
LGTM now that the starter label is ok.

**Pull request merged**
