### PR TITLE
fix: Update odo to 3.12.0

### LINKED ISSUE #570: Update to odo 3.12
[kind/Enhancement]

## Which functionality do you think we should update/improve?
update to latest odo

### PR DESCRIPTION
**Pull request by sbouchet**
See https://github.com/redhat-developer/odo/releases/tag/v3.12.0

fix #570

### CODE REVIEW

**Comment by sbouchet** [comment]
cc @mohitsuman

**Comment by adietish** [comment]
@sbouchet wondering if we shouldn't prompt the user to upgrade his existing odo binary?

**Review by adietish — APPROVED** [review]
Tooling downloaded odo `3.12.0` automatically, no asking. Shouldn't we prompt the user that we're downloading and saving onto his system?
Odo command line does that:
```bash
➜  intellij-openshift-connector git:(odo-3.12.0) ✗ odo version
odo v3.11.0 (b481d4c41)

Server: https://192.168.64.6:8443
Kubernetes: v1.26.3

---
A newer version of odo (v3.12.0) is available,
visit https://github.com/redhat-developer/odo/releases to update.
If you wish to disable this notification, run:
odo preference set UpdateNotification false
---
```

The other thing that I noticed is that an `odo` binary that already exists on my `$PATH` is ignored. The plugin is always using the binary that it downloads to `~/.odo/cache`. Shouldn't we try to use the one on the path?

**Comment by sbouchet** [comment]
> Tooling downloaded odo `3.12.0` automatically, no asking. Shouldn't we prompt the user that we're downloading and saving onto his system? 

should be the case. i'll open an issue for that.


>Odo command line does that:
> 
> ```shell
> ➜  intellij-openshift-connector git:(odo-3.12.0) ✗ odo version
> odo v3.11.0 (b481d4c41)
> 
> Server: https://192.168.64.6:8443
> Kubernetes: v1.26.3
> 
> ---
> A newer version of odo (v3.12.0) is available,
> visit https://github.com/redhat-developer/odo/releases to update.
> If you wish to disable this notification, run:
> odo preference set UpdateNotification false
> ---
> ```

this is currently the case when using released version with old odo 3.11, all odo output prints this message.

> 
> The other thing that I noticed is that an `odo` binary that already exists on my `$PATH` is ignored. The plugin is always using the binary that it downloads to `~/.odo/cache`. Shouldn't we try to use the one on the path?
> 
> I can create an issue if you want me to.

yes please !

**Comment by sbouchet** [comment]
> > Tooling downloaded odo `3.12.0` automatically, no asking. Shouldn't we prompt the user that we're downloading and saving onto his system?
> 

silent mode added in file with https://github.com/redhat-developer/intellij-openshift-connector/commit/474890023d6864a71a31c0b32f51af516e9bbe24,

**Comment by sbouchet** [comment]
created #571 to propose a preference/setting page to change behavior

**Comment by jeffmaury** [comment]
Just to remind you that I removed user notification because it caused a lot of issues that were hard to diagnostic: odo is required by the tooling so asking user does not make sense. If we coud we should have odo embedded into the plugin (as for VSCode) but that would greatly increase the plugin size as marketplace does not support platform selection

**Pull request merged**
