### PR TITLE
docs: add repository map to README.md

### PR DESCRIPTION
**Pull request by alexkarezin**
## What is the purpose of this change? What does it change?
Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/redhatdeveloperintellijopenshiftconnector/). Built directly from source and updated on schedule. In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.

## Was the change discussed in an issue?
Documentation-only change. Intended to simplify developer's introduction to the project.

## How to test changes?
README.md is the only document affected

### CODE REVIEW

**Review by adietish — APPROVED** [review]
Looks go to me. Thanks for the contribution!

**Review by sbouchet — APPROVED** [review]
LGTM. thanks for the contribution !

**Pull request merged**
