### PR TITLE
chore: update intellij-common-ui-test-library to v0.4.1

### PR DESCRIPTION
**Pull request by martinszuc**

### CODE REVIEW

**Comment by sbouchet** [comment]
@martinszuc is this supposed to fix Cluster/Public Integration tests failures ?

**Comment by martinszuc** [comment]
> @martinszuc is this supposed to fix Cluster/Public Integration tests failures ? 

@sbouchet yes it's the newest release of the library from yesterday

**Review by sbouchet — APPROVED** [review]
LGTM

**Pull request merged**
