### PR TITLE
chore: disable service tests

### PR DESCRIPTION
**Pull request by sbouchet**
## Was the change discussed in an issue?
see https://github.com/redhat-developer/service-binding-operator#deprecation-notice
and 404 while trying to install a compliant service (https://operatorhub.io/install/stable/cloud-native-postgresql.yaml)

### CODE REVIEW

**Review by adietish — APPROVED** [review]
LGTM beside the nitpicks. I tend to think that comment(s) on why why disable service tests would help for later.

**Comment by sbouchet** [comment]
seems all my @Ignore comments are... ignored :D

**Comment by sbouchet** [comment]
reverting IJ gradle plugin to 2.0.1 due to https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1834

**Comment by adietish** [comment]
/override "Integration UI Tests with Local Kind Cluster Context Report"

**Pull request merged**
