### PR TITLE
fix: readme: removed cdk, minishift. renamed CRC to OpenShift Local (…

### LINKED ISSUE #909: Remove reference of CRC and CDK from readme
## What did you find missing in the documentation?

We need to remove the CRC reference with OpenShift Local in the Readme. And also remove the reference of CDK and older versions of OCP 3.x.

## What is the relevance of it?

We need to keep the reference updated with the latest naming convention followed by OpenShift.

### PR DESCRIPTION
**Pull request by adietish**
fixes #909

### CODE REVIEW

**Comment by adietish** [comment]
@mohitsuman: please review

**Review by sbouchet — APPROVED** [review]
LGTM.

**Comment by adietish** [comment]
/override "Conventional Commits PR Check / Cluster Integration UI Tests Report"

**Pull request merged**
