### PR TITLE
docs: fix headers

### LINKED ISSUE #678: Missing copyright headers / missmatching copyright headers
[kind/Documentation]

## What did you find missing in the documentation?
those 3 files does not have headers 
./src/it/java/org/jboss/tools/intellij/openshift/test/ui/common/CreateComponentFixture.java
./src/main/java/org/jboss/tools/intellij/openshift/actions/component/DevOnPodmanComponentAction.java
./src/main/java/org/jboss/tools/intellij/openshift/ui/registry/CreateRegistryDialog.java

those 20 files does not refer to correct EPL v2.0 license
./src/main/java/org/jboss/tools/intellij/openshift/oauth/AccountStatus.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/DefaultTokenProvider.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/LoginProvider.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/LoginResponse.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/OAuthCoreConstants.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/OAuthUtils.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/exception/OAuthConfigurationException.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/exception/OAuthException.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/exception/OAuthLoginException.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/exception/OAuthRefreshException.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/model/AuthorizationServer.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/model/IAccount.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/model/IAccountModel.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/model/IAuthorizationServer.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/model/Account.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/model/AccountModel.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/ui/DefaultLoginProvider.java
./src/main/java/org/jboss/tools/intellij/openshift/oauth/AccountService.java
./src/main/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtils.java
./src/test/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtilsTest.java

### PR DESCRIPTION
**Pull request by sbouchet**
## Was the change discussed in an issue?
fixes #678

### CODE REVIEW

**Review by adietish — APPROVED** [review]
lgtm

**Comment by sbouchet** [comment]
/override ci/prow/e2e-openshift/override ci/prow/e2e-openshift

**Pull request merged**
