### PR TITLE
fix: dont refresh tree if binary is not downloaded (#802)

### LINKED ISSUE #802: Helm repositories that I expanded are collapsed again
**Steps:**
1. EXEC: expand "Helm Repositories"
2. ASSERT: child node "Loading..." is shown

**Result:**
"Helm Repositories" is collapsed again and I have to expand it a 2nd time. It then loads a 2nd time.
https://github.com/redhat-developer/intellij-openshift-connector/assets/25126/668422d1-6eae-4ce5-99ec-25b36cb44387

### PR DESCRIPTION
**Pull request by adietish**
fixes #802
depends on https://github.com/redhat-developer/intellij-common/pull/228

### CODE REVIEW

**Comment by adietish** [comment]
@sbouchet: we're back at jenkins not authenticating and thus intellij-common `1.9.6-SNAPSHOT` is missing and this PR not compiling:
>[2024-05-08T16:38:13.310Z] * What went wrong:
[2024-05-08T16:38:13.310Z] Execution failed for task ':publishMavenJavaPublicationToJbossNexusRepository'.
[2024-05-08T16:38:13.310Z] > Failed to publish publication 'mavenJava' to repository 'jbossNexus'
[2024-05-08T16:38:13.310Z]    > Could not PUT 'https://repository.jboss.org/nexus/content/repositories/snapshots/com/redhat/devtools/intellij/intellij-common/1.9.6-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized
[2024-05-08T16:38:13.310Z]

**Comment by sbouchet** [comment]
@adietish integration Tests have compilation failures : 
```
/home/runner/work/intellij-openshift-connector/intellij-openshift-connector/src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliTest.java:29: error: incompatible types: Tool<Odo> cannot be converted to Odo
> Task :compileIntegrationTestJava FAILED
        Odo odo = ToolFactory.getInstance().createOdo(getProject()).get();
                                                                       ^
/home/runner/work/intellij-openshift-connector/intellij-openshift-connector/src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliTest.java:32: error: incompatible types: Tool<Helm> cannot be converted to Helm
        this.helm = ToolFactory.getInstance().createHelm(getProject()).get();
                                                                          ^
/home/runner/work/intellij-openshift-connector/intellij-openshift-connector/src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliTest.java:38: error: incompatible types: Tool<Odo> cannot be converted to Odo
        Odo odo = ToolFactory.getInstance().createOdo(getProject()).get();
                                                                       ^
/home/runner/work/intellij-openshift-connector/intellij-openshift-connector/src/it/java/org/jboss/tools/intellij/openshift/utils/ToolFactoryTest.java:22: error: incompatible types: Tool<Odo> cannot be converted to Odo
        Odo odo = ToolFactory.getInstance().createOdo(getProject()).get();
                                                                       ^
/home/runner/work/intellij-openshift-connector/intellij-openshift-connector/src/it/java/org/jboss/tools/intellij/openshift/utils/ToolFactoryTest.java:27: error: incompatible types: Tool<Helm> cannot be converted to Helm
        Helm helm = ToolFactory.getInstance().createHelm(getProject()).get();
                                                                          ^
/home/runner/work/intellij-openshift-connector/intellij-openshift-connector/src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java:89: error: incompatible types: Tool<Odo> cannot be converted to Odo
      .thenApply(odoDelegate -> new ApplicationRootNodeOdo(odoDelegate, mock(ApplicationsRootNode.class), processHelper));
```

**Comment by adietish** [comment]
@sbouchet: corrected. Please re-review. thanks.

**Comment by adietish** [comment]
@sbouchet please review

**Review by sbouchet — APPROVED** [review]
LGTM. very good UI contribution !

**Pull request merged**
