### PR TITLE
fix: 'Delete Project' label is confusing when using kubernetes cluster

### LINKED ISSUE #708: Delete Project label is confusing when using kubernetes cluster
[kind/Enhancement]

## Which functionality do you think we should update/improve?
following #701, this request is to change the "delete project" defaut action label to delete anmespace when current cluster is kubernetes. also related issue #495

### PR DESCRIPTION
**Pull request by sbouchet**
## What is the purpose of this change? What does it change?
use Project/namespace words according to current cluster kind

## Was the change discussed in an issue?
fixes #708

### CODE REVIEW

**Comment by sbouchet** [comment]
adding also some text in the dialog to inform users about deleting all resources associated with the namespace/project (see #495)
Capture d’écran du 2024-04-22 19-51-09

**Review by adietish — APPROVED** [review]
LGTM

**Comment by adietish** [comment]
@sbouchet: IT's are failing with the details reported here: https://github.com/redhat-developer/intellij-openshift-connector/pull/801#issuecomment-2073305331. I suspect ff3707680f9bb43c03496495d20eda9b0327f3e2 causing this.

**Comment by sbouchet** [comment]
> @sbouchet: IT's are failing with the details reported here: [#801 (comment)](https://github.com/redhat-developer/intellij-openshift-connector/pull/801#issuecomment-2073305331). I suspect [ff37076](https://github.com/redhat-developer/intellij-openshift-connector/commit/ff3707680f9bb43c03496495d20eda9b0327f3e2) causing this.

main branch with this commit is building fine, wuithout IT failures. checking what's going on.

**Comment by sbouchet** [comment]
@adietish more like https://github.com/redhat-developer/intellij-openshift-connector/pull/781 , but unclear why it's failling now.

**Pull request merged**
