### PR TITLE
feat: Add support for service creation

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

## Was the change discussed in an issue?
fixes #???

### CODE REVIEW

**Review by sbouchet — APPROVED** [review]
LGTM.

**Comment by mohitsuman** [comment]
@jeffmaury can you please add the UI gif/demo of how the service creation workflow looks like.

**Comment by mohitsuman** [comment]
have we not added a UI to ask for the service creation parameters? If you can share the screenshots too, that will be nice.

**Comment by jeffmaury** [comment]
> have we not added a UI to ask for the service creation parameters? If you can share the screenshots too, that will be nice.

No it's the same old one: https://github.com/redhat-developer/intellij-openshift-connector#operator-based-services

**Comment by sbouchet** [comment]
fixes #484

**Review by sbouchet — APPROVED** [review]
LGTM

**Pull request merged**
