### PR TITLE
chore: Remove unnecessary files

### PR DESCRIPTION
**Pull request by sbouchet**
## What is the purpose of this change? What does it change?
remove not needed files

### CODE REVIEW

**Review by adietish — APPROVED** [review]
image
This icon indeed isn't used anywhere in the plugin.

**Comment by sbouchet** [comment]
> image
> This icon indeed isn't used anywhere in the plugin. We should maybe use it as cluster icon though to match what vscode is using.

@adietich there is two icons, one in  the images directory (openshift_extension.png) and oone in the META-INF (openshiftpluginicon13*13.png ) . the later is the one used for the view and must remain, the other one in the feedback dialog. 

which one do you refer to ?

**Pull request merged**
