### PR TITLE
fix: remove open console action.

### LINKED ISSUE #567: Move open dashboard action to kubernetes
[kind/Enhancement]

## Which functionality do you think we should update/improve?
when https://github.com/redhat-developer/intellij-kubernetes/issues/617 will be merged, our own open console will be a duplicate.

### PR DESCRIPTION
**Pull request by sbouchet**
## Was the change discussed in an issue?
fixes #567

### CODE REVIEW

**Comment by adietish** [comment]
@sbouchet: current failures in checks are caused because checks are run against main, correct?

**Review by adietish — APPROVED** [review]
lgtm. I ran test locally on the branch and they are fine.

**Comment by sbouchet** [comment]
@adietish Cluster UI integration tests are failling since a while. with no obvious reasons. 
i agree that this is not ideal but we can't use the fork as running branch, as we use a gpg secret key to use IDEA Ultimate.

**Comment by adietish** [comment]
/override Conventional Commits PR Check / Cluster Integration UI Tests Report

**Comment by adietish** [comment]
/override Conventional Commits PR Check / Cluster Integration UI Tests Report (pull_request_target)

**Pull request merged**
