### PR TITLE
fix: Anonymise error messages by removing exception handling

### LINKED ISSUE #855: Anonymise error messages
## What versions of software are you using?
- Operating System:
- IntelliJ version:
- Extension version:
- Are you targeting a kubernetes or an Openshift cluster ? If possible, provide its version:

## Actual behavior

When an error is sent using telemetry, the message can display remote cluster URL.

## Expected behavior

there is already an anonymise method but it's not called when using direclty the exception.

### PR DESCRIPTION
**Pull request by sbouchet**
## Was the change discussed in an issue?
fixes #855

### CODE REVIEW

**Review by adietish — COMMENTED** [review]
Wondering why things are not anonymized. I see your error being sent to `com.redhat.devtools.intellij.telemetry.core.service.Message.error(message)` which is as follows:

```java
  public T error(String message) {
        this.property("error", AnonymizeUtils.anonymize(message));
        return this.clearResult();
    }
```
What am I missing?

**Review by adietish — APPROVED** [review]
LGTM

**Comment by adietish** [comment]
@sbouchet: can you please explain why this needs to be on hold?

**Comment by sbouchet** [comment]
was holding while preparing 1.10.0. release. un holding since fix i likely to take some time to implement

**Review by adietish — APPROVED** [review]
LGTM

**Pull request merged**
