### PR TITLE
feat: add feedback dialog

### LINKED ISSUE #554: Add feedback section for the extension
There should be a button `Share Feedback for extension` on the extension view and it open up a view to collect feedback.

### PR DESCRIPTION
**Pull request by sbouchet**
## What is the purpose of this change? What does it change?
Added a toolbar icon/action to share feedback using telemetry backend

## Was the change discussed in an issue?
fixes #554

### CODE REVIEW

**Comment by adietish** [comment]
I see the top section of the feedback dialog using a different font than the rest of the dialog:
image

**Comment by sbouchet** [comment]
> I see the top section of the feedback dialog using a different font than the rest of the dialog: image I think that the dialog title bar would better show priorities if the icons and title would be reshuffled. Here's a suggestion: image

it's a webpage, taken from the vscode extension. @mohitsuman can you comment ?

**Comment by adietish** [comment]
I would also layout the labels/text area differently, following the jetbrains [design guide](https://jetbrains.design/intellij/principles/layout/#labeled-input-controls)
image

**Comment by adietish** [comment]
> it's a webpage, taken from the vscode extension. @mohitsuman can you comment ?

If it's a web-page, why not open it in the browser like jetbrains do (choosing the menu item opens their web form)? 
image

image

**Comment by adietish** [comment]
I have another suggestion: On top of the whole form I'd add a way to rate the product in a single click, like one can find in the jetbrains form, on amazon product reviews etc.
image
My justification is that I usually dislike provide feedback. But when I do it, I do it if there's little work like clicking on a star-rating or similar. I usually dislike tedious writing in free text areas etc. I'd think most devs are in this state of mind. We could thus increase feedback rates by providing the simplest possible feedback: a star-rating.

**Comment by sbouchet** [comment]
by "webpage", i was referring to the webview implemented in vscode ( using a webpage input ) .
Your review made me think about removing that in favor of pure jface components.

**Comment by sbouchet** [comment]
Capture d’écran de 2023-07-13 16-58-04

dialog is now looking like this.

**Comment by adietish** [comment]
@sbouchet: I simplified code that shows/hides components, made links for github and marketplace use non-serifed font and changed the positioning a bit. Hope you like it, otherwise just pick what the changes that you agree with and throw out the rest.
image

**Comment by sbouchet** [comment]
thank for the contributions ! i've added a margin to the left to better visual feedback when scrollbar is showed.

**Comment by adietish** [comment]
@sbouchet: I simplified code that shows/hides components, made links for github and marketplace use non-serifed font and changed the positioning a bit. Hope you like it, otherwise just pick what the changes that you agree with and throw out the rest.

**Comment by adietish** [comment]
rebased it.

**Comment by mohitsuman** [comment]
@adietish @sbouchet can you please add a gif/image of how the final feedback view looks like and accordingly can review the  questions ?

**Comment by adietish** [comment]
here's a screenshot of the current state of it:
image

**Comment by sbouchet** [comment]
here is the rendering on my side (Fedora) 
Capture d’écran du 2023-08-14 17-26-08

**Comment by sbouchet** [comment]
the image size is way different from MacOs !

**Comment by sbouchet** [comment]
@adietish : seems like i missed the scaling factor for images, when using High DPI. can you check the rendering on your MacOS again ?

**Review by mohitsuman — CHANGES_REQUESTED** [review]
As discussed, let's do the following changes:

- Update the icon at the toolbar window and use the same one in VSCode
- Implement radio buttons to collect the ratings
- Remove dropdown with Switch Button
- Change the redirect link on `Rate us on Marketplace`
- Make the OpenShift Toolkit, GitHub and Marketplace on same line. And Your Opinion text in the next line.

**Comment by sbouchet** [comment]
Modified according to reviews : 

> As discussed, let's do the following changes:
> 
> * Update the icon at the toolbar window and use the same one in VSCode
Capture d’écran du 2023-08-22 12-23-57


> * Implement radio buttons to collect the ratings
> * Remove dropdown with Switch Button
> * Change the redirect link on `Rate us on Marketplace`
> * Make the OpenShift Toolkit, GitHub and Marketplace on same line. And Your Opinion text in the next line.


Capture d’écran du 2023-08-22 12-24-08

**Comment by adietish** [comment]
@sbouchet: Icons are cropped on MacOS and I am wondering if "Have you used any similar extension..." wasn't better off with checkboxes, too?
image

**Review by adietish — CHANGES_REQUESTED** [review]
I like your screenshot a lot. Quite an improvement, visually and usability-wise.
On MacOS though, icons are cropped. Futhermore I am wondering if "Have you used any similar extension..." wasn't better off with checkboxes, too?
image

**Comment by sbouchet** [comment]
Capture d’écran du 2023-08-22 18-17-26

**Review by adietish — CHANGES_REQUESTED** [review]
In terms of widgets and icons/images it's now great imho. But I noticed a weird behavior where I'm wondering if it's intentional:

**Steps:**
1. ASSERT: OK button is disabled
2. EXEC: Provide some text in "4. What, if anything..."
3. ASSERT: OK button is disabled
4. EXEC: provide some text that's not an email (ex. "dddd") in "Share your contact..."
5. ASSERT: OK button is disabled, text field gets red with a balloon "The email format should be..."
6. EXEC: delete the text in "Share your contact..."

**Result:**
OK button is enabled.
image

**Expected Result:**
If providing text in "4. What, if anything..." is enough to have a valid form, shouldn't the "OK" button get enabled as soon as I provide text to it, not just after filling in invalid email and removing it?

**Comment by sbouchet** [comment]
Fixed it. good catch !

**Comment by adietish** [comment]
@sbouchet I can still cause the "OK" button to get enabled when I add an invalid email and remove it again. Am I missing something?

**Review by mohitsuman — APPROVED** [review]
The UI looks good to merge.

**Comment by adietish** [comment]
> The UI looks good to merge.

Yes, I agree, but you're still able to send empty forms.

**Comment by adietish** [comment]
@sbouchet added a check for content. OK is not enabled if there's no content. Please review.

**Comment by adietish** [comment]
@sbouchet added a check which makes sure that there's content in any of the widgets. Please review.

**Comment by sbouchet** [comment]
> @sbouchet added a check which makes sure that there's content in any of the widgets. Please review.

nice ! works like a charm :)

**Pull request merged**
