### PR TITLE
chore(skip-release): corrected action label capitalizations

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Review by sbouchet — APPROVED** [review]
LGTM

**Comment by adietish** [comment]
@sbouchet ITs are failing with the following (cannot be caused by this PR that is only changes labels). Any idea what's wrong with the ITs?
```bash
    19:29:25,472 SEVERE                 #TestFramework - Test failed 
    java.io.IOException: Process exited with an error: 1 (Exit value: 1)  ✗  unable to parse devfile: failed to populateAndParseDevfile: unable to find schema for version "2.2.2". The parser supports devfile schema for version 2.0.0, 2.1.0, 2.2.0, v1alpha
```

**Comment by adietish** [comment]
@sbouchet ITs are now fixed, thanks!

**Pull request merged**
