### PR TITLE
Add debug documentation link

### LINKED ISSUE #140: Add debug action documentation
[kind/Documentation]

## What did you find missing in the documentation?

Document the new ODO debug action.

### PR DESCRIPTION
**Pull request by sbouchet**
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

## What is the purpose of this change? What does it change?
adding documentation link in the README

## Was the change discussed in an issue?
fixes #140

### CODE REVIEW

**Comment by sbouchet** [comment]
see wiki:  https://github.com/redhat-developer/intellij-openshift-connector/wiki/How-to-debug-a-component

**Comment by jeffmaury** [comment]
See my changes on the wiki page: https://github.com/jeffmaury/intellij-openshift-connector-wiki/tree/fix-debug

**Comment by sbouchet** [comment]
> See my changes on the wiki page: https://github.com/jeffmaury/intellij-openshift-connector-wiki/tree/fix-debug

changes pushed. 
As the version will change, maybe we should keep this PR open while the version is not released ?

**Comment by jeffmaury** [comment]
Why ? master is not production

**Comment by jeffmaury** [comment]
OK. I got your point. OK to keep it here until we released 0.2.0

**Pull request closed without merging**
