### PR TITLE
feat: display 'creating...' while component is being created (#552)

### LINKED ISSUE #524: As a user when create a new component, I cannot see that it accepted my action and is working
[kind/enhancement]

## What versions of software are you using?
- Operating System: MacOS
- IntelliJ version: HEAD
- OpenShift version: Red Hat sandbox

## What did you run exactly?
**Steps:**
1. ASSERT: make sure you're connected to the Red Hat Sandbox
2. EXEC: launch plugin
3. ASSERT: have the tree showing "modelmesh-controller" component
image
4. EXEC: pick "New Component" in the ctx menu to you project ("adietish-dev" in my case, that's the default project)

5. EXEC: in the upcoming dialog, select any type (ex. "Maven Java") and hit "Finish"
<br/><br/>

**Result:**
The dialog is closed and it looks as if nothing happens. 
image
It's only after maybe 30s that the tree gets refreshed and displays the new component
image

**Expected Result:**
I should get some feedback that my operation was accepted and is being processed, the component being created. 

Same when deleting the component:
**Steps:**
1. ASSERT: have a locally created component in your sandbox
image
2. EXEC: pick "Delete" in the context menu of your component & confirm the dialog that asks you if you're sure about deleting.
**Result:**
The tree seems unchanged, there's no progress, no "Loading..." or something else that would tell me that it is deleting the component. 
image
It's only after maybe 20s that the tree is refreshed and now doesn't show my component any more.
image

**Expected Result:**
I would like to have some progress bar or some other feedback that tells me that the plugin is deleting my component.

### LINKED ISSUE #552: Link Service action on non local component is visible
[kind/bug]

## What versions of software are you using?
- Operating System:
- IntelliJ version:
- OpenShift version:

## What did you run exactly?
using devsandbox, there is a modelmesh-controller component available for all. 
This component is not locally created, so there is no devfile for it.
all actions related to devfile manipulation should not be visible, like link service

## Expected behavior
Link service action should not be present

### PR DESCRIPTION
**Pull request by adietish**
fixes #524 
depends on https://github.com/redhat-developer/intellij-common/pull/195

### CODE REVIEW

**Comment by adietish** [comment]
@sbouchet: Please review. There are 2 node states that were added:
* when a node is deleted, the decoration label (light gray to the right of the main label) displays `Deleted`
* when a long running cmd is executed (ex. create a component), the child nodes to the namespace/project is replaced by a comment on what is being done (ex. "Creating component xxxx..."). This child node then disappears once the cmd is finished and replaced by "loading..." before the updated list of services/components is displayed.
Furthermore every action now displays a message in the status bar (ex. "Create component...").
It is important to test all available actions because they are all affected.

**Comment by adietish** [comment]
@sbouchet this now is only adding labels (ex. to the namespace node 'Creating component...') that disappear once new component is shown as child node. It feels faster and like it would be refreshing the tree less.

**Review by sbouchet — APPROVED** [review]
LGTM. very nice improvment in the UI.

**Comment by sbouchet** [comment]
this will also 
fixes #242

**Comment by sbouchet** [comment]
and also 
fixes #344

**Pull request merged**
